<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>feederdikti_importer</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DataFailed\Akuntansi_ltemReg_todo_failed.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <PackageReference Include="EPPlus" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataFailed\" />
  </ItemGroup>

</Project>